version: '3.8'
services:
  node:
    image: automatio/node:20.10.0-buster-slim
    build:
      context: node
  xvfb:
    image: automatio/xvfb:20.10.0-buster-slim
    build:
      context: xvfb
  puppeteer:
    image: automatio/xvfb-puppeteer:21.5.2
    build:
      context: puppeteer
