version: '3.8'
services:
  node:
    image: automatio/node:14.16.1-slim
    build:
      context: node
  xvfb:
    image: automatio/xvfb:14.16.1-buster-slim
    build:
      context: xvfb
  puppeteer:
    image: automatio/xvfb-puppeteer:10.0.0
    build:
      context: puppeteer
