version: '3.8'
services:
  prisma:
    image: automatio/prisma:1.34.8
    build:
      context: prisma
  node:
    image: automatio/node:14.16.1-slim
    build:
      context: node
  xvfb:
    image: automatio/xvfb:14.16.1-buster-slim
    build:
      context: xvfb
